### PR TITLE
Move bash completion to ~/.bash_completion which is apparently a thing

### PR DESCRIPTION
**Pull request by JamesSto**
@troyjoseph would you let me know if this works on Mac?

### CODE REVIEW

**Comment by DecSander** [comment]
still getting permission denied

also looks like there may be a quotation mark missing?

**Comment by JamesSto** [comment]
Missing quotation mark where?

Also permission denied for what? Make sure you delete the data/ directory and the bash_completion.d/jump-directory before running this new setup script.

**Comment by DecSander** [comment]
nvr mind, looks like it worked :+1:

**Comment by DecSander** [comment]
oh wait, now i'm getting 
```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
```

**Comment by JamesSto** [comment]
Does greadlink support the same flags as readlink? -f and -e?

Huh it does... when do you see that happening?

**Comment by DecSander** [comment]
looks like it does in the help

**Comment by JamesSto** [comment]
When do you see that happening? Anytime you call jd?

**Comment by troyjoseph** [comment]
greadlink supports the same flags as readlink

@DecSander are you sure this works? I don't think this will work on Mac without adding to .bash_profile to source .bash_completion. I think the brew method is the more generic way to do this.

**Comment by DecSander** [comment]
it looks like it found the bash_completion file, it happens everytime i call cd

**Comment by JamesSto** [comment]
Is the ~/.bash_completion file not sourced on mac?

**Comment by troyjoseph** [comment]
I'm confused. Why would .bash_completion get loaded? Are you sure you've deleted the other places the program is installed before trying this?

**Comment by JamesSto** [comment]
http://iseborn.eu/wiki/index.php?title=Ubuntu/Setting_up_bash_completion

Yeah, I did. I guess if ~/.bash_completion isn't a thing on mac it'd be easy enough to just put it in the profile or bashrc

**Comment by DecSander** [comment]
i think it does get sourced

**Comment by troyjoseph** [comment]
confirmed, the brew install does source that file.

**Comment by JamesSto** [comment]
So this new setup script works? Or is there some other issue?

**Comment by troyjoseph** [comment]
it can work. Updated the readme for how to properly install on mac.

**Comment by JamesSto** [comment]
Is there some reason that this can't be just automatically included in the setup script?

**Pull request merged**
